# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9258f0ddad0bc8d1a980cbe5a793b2836610d19c349e22bc520856901570e3ad9f73498de6c33a949b6a18671be4804c9cc0e3083162eba678186eacc66f7212

test:
  secret_key_base: 1345bec1725d39cabb7b210523a3a340ed81cf127956a5d64f09d29e994633e17f86f9962d1f29108aa54238943ae57768ac879079e80babac38e1f3aec89889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
